duration: 30 # duration for running the script (including baselne period) in seconds
dark_screen_duration: 10   # duration for the initial dark screen (baseline period) in seconds
use_fictrac: false  # Set to true to enable FicTrac integration
debug: false  # Global debug flag - enables detailed output for all processes
use_arduino: true  # Whether to use an arduino to send a hardware trigger to the 2P Microscope at the start of the experiment and subsequent handshakes

# Display settings
# Width of the projected image in pixels that matches the bowl setup, i.e if the projected image's width matches the bowl's width,
# you are using all 1280 pixels along the width for stimulus presentation (for a 1280x720 projector)
projector_width_pixels: 1280  

# Arduino settings
arduino_port: "COM3"  # Serial port for Arduino communication
arduino_baudrate: 115200  # Baud rate for Arduino communication
arduino_handshake_interval: 1  # Interval in seconds for Arduino handshake

# Noise pattern settings
noise:
  framerate: 10  # The number of frames refreshes (in Hz) (new noise pattern generated)
  pixel_size: 10  # Size of noise pixels in degrees (the bowl is 140 degrees in elevation and 180 degrees in azimuth)
  save_path: "C:\\Users\\theru\\julianarhee\\data\\20250908"  # Directory where frames will be saved
  file_name: "20250908_Dmel_R35D04-R22D06-RSET-GCaMP8m_005"  # Base name for the saved HDF5 file

# FicTrac settings (only used if use_fictrac is true)
fictrac:
  host: "127.0.0.1"
  port: 3000
  output_csv: "fictrac.csv"

# moving_dot:
#   elevation: 70
#   elevation_width: 5
#   azi_limits: [0, 180]
#   speed: 50